---
- name: mikrotik backup
  hosts: 192.168.10.2
  gather_facts: no

  tasks:
    - name: export config
      routeros_command: 
        commands: 
          - /export
      register: foo_stdout
    - name: save config
      copy:
        content: "{{ foo_stdout.stdout }}"
        dest: /mnt/c/git/ansible-examples/mikrotik/backups/test.txt 